stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - apt install libsqlite3-dev
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  allow_failure: true
  script:
    - apt install libsqlite3-dev
    - cargo build --verbose
    - cargo test --verbose
