stages:
  - build

variables:
  # We don't need Husky to install the Git hooks for CI.
  CARGO_HUSKY_DONT_INSTALL_HOOKS: "true"

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose --target x86_64-unknown-linux-gnu
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  allow_failure: true
  script:
    - cargo build --verbose --target x86_64-unknown-linux-gnu
    - cargo test --verbose
