[workspace]

# Here we declare that this is a workspace, containing several crates
# within it.
members = [
    "caret",
    "tor-llcrypto",
    "tor-protover",
    "tor-bytes",
    "tor-socks",
    "tor-checkable",
    "tor-cert",
    "tor-linkspec",
    "tor-cell",
    "tor-proto",
    "tor-netdoc",
    "tor-netdir",
    "tor-chanmgr",
    "tor-circmgr",
    "client-demo",
    ]