[package]
name = "tor-bytes"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
tor-llcrypto = { path="../tor-llcrypto" }

arrayref = "0.3.6"
generic-array = "0.14.4"
crypto-mac = "0.9.1"
thiserror = "1.0.20"
signature = "1.2.2"
bytes = "0.5.6"

[dev-dependencies]
hex-literal = "0.3.1"

