[package]
name = "tor-dirmgr"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = []
legacy-store = []

[dependencies]
tor-chanmgr = { path="../tor-chanmgr", version= "*" }
tor-checkable = { path="../tor-checkable", version= "*" }
tor-circmgr = { path="../tor-circmgr", version= "*" }
tor-dirclient = { path="../tor-dirclient", version= "*" }
tor-netdir = { path="../tor-netdir", version= "*" }
tor-netdoc = { path="../tor-netdoc", version= "*" }
tor-llcrypto = { path="../tor-llcrypto", version= "*" }
tor-rtcompat = { path="../tor-rtcompat", version= "*" }

anyhow = "1.0.34"
async-rwlock = "1.3.0"
async-trait = "0.1.42"
base64 = "0.13.0"
chrono = "0.4.19"
digest = "0.9.0"
event-listener = "2.5.1"
futures = "0.3.8"
hex = "0.4.2"
log = "0.4.11"
memmap = "0.7.0"
rand = "0.7.3"
rusqlite = { version="0.24.1", features=["chrono"] }
thiserror = "1.0.22"

[dev-dependencies]
futures-await-test = "0.3.0"
hex-literal = "0.3.1"
tempdir = "0.3.7"
