[package]
name = "tor-netdoc"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
tor-llcrypto = { path="../tor-llcrypto", version="*" }
tor-cert = { path="../tor-cert", version="*" }
tor-protover = { path="../tor-protover", version= "*" }

digest = "0.9.0"
phf = { version = "0.8.0", features = ["macros"] }
hex = "0.4.2"
lazy_static = "1.4.0"
base64 = "0.12.3"
thiserror = "1.0.20"
chrono = "0.4.15"
signature = "1.2.2"
