[package]
name = "tor-llcrypto"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
aes-ctr = "0.6.0"
arrayref = "0.3.6"
base64 = "0.13.0"
curve25519-dalek = "3.0.0"
digest = "0.9.0"
ed25519-dalek = { version = "1.0.1", features = ["batch"] }
hex = "0.4.2"
num-bigint = "0.3.0"
num-traits = "0.2.12"
rsa = "0.3.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
sha3 = "0.9.1"
signature = "1.2.2"
simple_asn1 = "0.5.0"
subtle = "2.3.0"
x25519-dalek = "1.1.0"
zeroize = "1.1.1"

[dev-dependencies]
hex-literal = "0.3.1"
rand = "0.7.3"
cipher = "0.2.1"

# This is a magic crate that runs the tests and checks the format
# before it lets you commit or push.  It installs git hooks for this whenever
# you say "cargo test".
[dev-dependencies.cargo-husky]
version = "1.5.0"
features = ["precommit-hook", "run-cargo-test",
            "run-cargo-fmt", "run-for-all" ]
