[package]
name = "tor-llcrypto"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arrayref = "0.3.6"
digest = "0.9.0"
typenum = "1.12.0"
generic-array = "0.14.4"
aes-ctr = "0.4.0"
zeroize = "1.1.0"
rsa = "0.3.0"
simple_asn1= "0.4.1"
subtle = "2.2.3"
# Can't upgrade past this because of aes-ctr crate! Why?
stream-cipher = "^0.4"
num-traits = "0.2.12"
num-bigint = "0.3.0"
curve25519-dalek = "3.0.0"
x25519-dalek = "1.0.1"
ed25519-dalek = "1.0.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
sha3 = "0.9.1"
signature = "1.2.2"
hex = "*"

[dev-dependencies]
hex-literal = "0.3.1"

# This is a magic crate that runs the tests and checks the format
# before it lets you commit or push.  It installs git hooks for this whenever
# you say "cargo test".
[dev-dependencies.cargo-husky]
version = "1.5.0"
features = ["precommit-hook", "run-cargo-test",
            "run-cargo-fmt", "run-for-all" ]
