[package]
name = "tor-proto"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
caret = { path="../caret" }
tor-llcrypto = { path="../tor-llcrypto" }
tor-bytes = { path="../tor-bytes" }

arrayref = "0.3.6"
digest = "0.9.0"
rand = "0.7.3"
typenum = "1.12.0"
# XXXX why did I have to downgrade?
generic-array = "0.14.4"
rand_core = "0.5.1"
crypto-mac = "0.9.1"
hmac = "0.9.0"
hkdf = "0.9.0"
zeroize = "1.1.0"
subtle = "2.2.3"
stream-cipher = "0.7.1"
sha2 = "0.9.1"

[dev-dependencies]
hex-literal = "0.3.1"

