[package]
name = "tor-proto"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
caret = { path="../caret" }
tor-llcrypto = { path="../tor-llcrypto" }
tor-bytes = { path="../tor-bytes" }

arrayref = "*"
digest = "*"
rand = "*"
typenum = "*"
# XXXX why did I have to downgrade?
generic-array = "0.12"
rand_core = "*"
crypto-mac = "*"
hmac = "*"
hkdf = "0.9.0-alpha.0"
zeroize = "*"
subtle = "*"
stream-cipher = "*"
sha2 = "*"

[dev-dependencies]
hex-literal = "*"

