name: Build and publish

on:
  workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      artifact_name: sqlite3.dll

        steps:
            - uses: actions/checkout@v2

            - run: mkdir target

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              run: cargo build -p arti --locked --release

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
